# fly.toml app configuration file generated for new-api-proxy on 2024-04-11T16:14:06+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'new-api-proxy'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
